id: 
name: GitOps.PullRequestIssueManagement
description: GitOps.PullRequestIssueManagement primitive
owner: 
resource: repository
disabled: false
where: 
configuration:
  resourceManagementConfiguration:
    scheduledSearches: []
    eventResponderTasks:
    - if:
      - payloadType: Pull_Request
      - hasLabel:
          label: auto-merge
      then:
      - enableAutoMerge:
          mergeMethod: Squash
      description: 
    - if:
      - payloadType: Pull_Request
      - labelRemoved:
          label: auto-merge
      then:
      - disableAutoMerge
      description: 
    - if:
      - payloadType: Pull_Request
      - hasLabel:
          label: dependencies
      - not:
          hasLabel:
            label: auto-merge
      - isActivitySender:
          user: dependabot[bot]
          issueAuthor: False
      then:
      - approvePullRequest:
          comment: ':shipit:'
      - addLabel:
          label: auto-merge
      description: 
onFailure: 
onSuccess: 
