<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <NoWarn>$(NoWarn);1591</NoWarn>
    <BicepExtensionName>MagicEightBall</BicepExtensionName>
    <BicepExtensionVersion>2.0.0</BicepExtensionVersion>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Azure.Deployments.Extensibility.Hosting.Managed\Azure.Deployments.Extensibility.Hosting.Managed.csproj" />
  </ItemGroup>

  <Import Project="..\..\src\Azure.Deployments.Extensibility.Hosting.Managed\buildTransitive\Azure.Deployments.Extensibility.Hosting.Managed.targets" />

</Project>
