apiRules:
  - exclude:
      uidRegex: ^System\.
      type: Namespace
  - exclude:
      uidRegex: ^Microsoft\.
      type: Namespace
  - include:
      uidRegex: ^Azure\.Deployments\.Extensibility\.
      type: Namespace
  - exclude:
      hasAttribute:
        uid: System.ObsoleteAttribute
      type: Member
  - exclude:
      hasAttribute:
        uid: System.Runtime.CompilerServices.InternalsVisibleToAttribute
      type: Member
  - exclude:
      uidRegex: ^Azure\.Deployments\.Extensibility\.Core\.(IExtensibilityProvider|IExtensibilityProviderRegistry|ModelMapper|Extensib|ExtensibleImport|ExtensibleResource)
      type: Type
  - exclude:
      uidRegex: ^Azure\.Deployments\.Extensibility\.Core\.Exceptions\.
      type: Type
  - exclude:
      uidRegex: ^Azure\.Deployments\.Extensibility\.Core\.Extensions\.
      type: Type
  - exclude:
      uidRegex: ^Azure\.Deployments\.Extensibility\.Core\.Json\.(ExtensibilityJsonSerializer|ExtensibilityOperationResponseConverter|ObjectElement)
      type: Type
  - exclude:
      uidRegex: ^Azure\.Deployments\.Extensibility\.Core\.Validators\.
      type: Type
