name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      DOTNET_NOLOGO: true # don't print dotnet logo
      DOTNET_CLI_TELEMETRY_OPTOUT: true # disable telemetry (reduces dotnet tool output in logs)
      CI: true

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0 # avoid shallow clone so nbgv can do its work.

      - name: Setup .NET Core
        uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68 # v6.0.0
        with:
          global-json-file: global.json

      - name: Build
        run: dotnet build Azure.Deployments.Extensibility.sln --configuration release

      - name: Run unit test
        run: dotnet test Azure.Deployments.Extensibility.sln --filter "Category=Unit" --configuration Release --collect:"XPlat Code Coverage"

      - name: Start minikube
        uses: medyagh/setup-minikube@latest

      - name: Run integration test
        run: dotnet test Azure.Deployments.Extensibility.sln --filter "Category=Integration" --configuration Release --collect:"XPlat Code Coverage"

      - name: Pack
        run: dotnet pack Azure.Deployments.Extensibility.sln --configuration release

      - name: Upload NuGet packages
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: bicep-extensibility-packages
          path: ./out/*
          if-no-files-found: error

      - name: Upload Code Coverage
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        with:
          # TODO: remove after the repo goes public
          token: ${{ secrets.CODECOV_TOKEN }}
